export const START_FETCH_CITY = 'START_FETCH_CITY';
export const  FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS';
export const FETCH_CITY_FAIL = 'FETCH_CITY_FAIL';
export const SEARCH_CITY_VALUE = 'SEARCH_CITY_VALUE';
export const SET_CITY_ID = 'SET_CITY_ID';
export const SHOW_CITY_DROPDOWN = 'SHOW_CITY_DROPDOWN';